namespace HTM.Enums
{
    public enum BasisBlockType
    {
        NotApplicable,
        SingleBasisBlock,
        FrontSBB,
        BackSBB,
        LeftSBB,
        RightSBB,
        UpSBB,
        BottomSBB,
        DoubleBasisBlock,
        FUDBB,
        FBDBB,
        LUDBB,
        LBDBB,
        BUDBB,
        BBDBB,
        RUDBB,
        RBDBB,
        NormalBlock,
        CoreBasisBlock,
        FrontLeftBottomCBB,
        FrontRightBottomCBB,
        FrontLeftUpperCBB,
        FrontRightUpperCBB,
        BackLeftBottomCBB,
        BackRightBottomCBB,
        BackLeftUpperCBB,
        BackRightUpperCBB
    }
}
